version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: 'Setup Environment Variables'
          command: |
            echo 'export CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID"' >> $BASH_ENV
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - restore_cache:
          key: 'node-v1-{{ checksum "package.json" }}'
      - restore_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}'
      - run:
          name: 'Install dependencies'
          command: 'yarn'
      - save_cache:
          key: 'node-v1-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - save_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}'
          paths:
            - ~/.cache/yarn
      - run:
          name: 'Run tests and get coverage'
          command: 'yarn test:ci'
      - run:
          name: 'Send test coverage to CodeClimate'
          command: |
            ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
            ./cc-test-reporter upload-coverage

workflows:
  testing:
    jobs:
      - test
